### ISSUE TITLE
Chess.uci missing

### ISSUE THREAD

**Issue by infinitless** [mptedesco/python-chess-analysis#3]
I am a beginner in Python and tried to run (copy-pasted) this code in PyCharm. Gives an error saying chess.uci not found. Not sure what to do really. Can this code be re-written to newer adjustments without chess.uci?! :(

**Comment by mptedesco** [comment]
Do you have the python-chess package installed?  This program needs that library.  I have not updated this in quite some time so there could be some issues related to versions - I'll need to check.  But I suspect the issue is you do not have the python-chess library installed?

https://python-chess.readthedocs.io/en/latest/

**Comment by infinitless** [comment]
I have the Python Chess installed yes. But from what I have googled the chess.uci module is no longer supported. It has been replaced by Chess.Engine and therefore all the functions have changed! This is some great code and it would be absolutely awesome to get it running - I understand the ideas are from Alexandre Shashin's book - Best Play(?). 
In fact someone made an engine on Github claiming that it mirrors the ideas in the book (ShashChess) - however, that is just modified Stockfish and therefore false claim.
Would be great to have this updated!!! Well done on the code!!

**Comment by mptedesco** [comment]
Thanks for the heads up - I didn't realize that the chess.UCI had been replaced.  When I have some time, I'll look at updating this and make some other improvements.  I was definitely influenced by Shashin's Best Play.   Great book!

**Comment by infinitless** [comment]
Great! Please let us know when done! I am keen to use this code and see how it goes! Thanks!

**Comment by cja000** [comment]
Hi,
I have refactor the code and make it compatible with `chess.engine`
There is a commit in Pull request just in case you want to have a look at it

**Comment by infinitless** [comment]
> Hi, I have refactor the code and make it compatible with `chess.engine` There is a commit in Pull request just in case you want to have a look at it

Thank you so much!!! I realised this is a message for the author, but I still want to say Thank You!

**Comment by infinitless** [comment]
Not sure what I am missing - I basically copy pasted the code into Pycharm. Set my folder paths etc. and there are errors w.r.t unresolved references to infohandler. and %%time 🤷‍♂️

**Comment by cja000** [comment]
Could you paste the exact errors?
`%%time` is an inline function of iPython to measure the time in that cell. You can remove it.
Which version of `python-chess`are you using?
```
(py39) D:\>python -c "import chess; print(chess.__version__)"
1.8.0
```

**Comment by infinitless** [comment]
Yep, I am using 1.8.0. and PyCharm. 
I commented # the %%time. Now I get the following errors:
Plies: 108
Timer per ply: 0.06 seconds
Traceback (most recent call last):
  File "C:.\Chess\main.py", line 257, in <..module>
    engine.quit()
  File "C:...Python\Python310\lib\site-packages\chess\engine.py", line 2783, in quit
    with self._not_shut_down():
  File "C:...Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:...Python\Python310\lib\site-packages\chess\engine.py", line 2713, in _not_shut_down
    raise EngineTerminatedError("engine event loop dead")
chess.engine.EngineTerminatedError: engine event loop dead

**Comment by cja000** [comment]
Could you post the PGN file?
Which engine are you using?

It is very rare to give an error in the `engine.quit()`.
It is like the engine is hanged.
Try to remove that line. The processing is already done but I don't like to leave process open.

I haven't used or read about Python 3.10.
I don't know if it could be the problem.

**Comment by infinitless** [comment]
Sure, it is this one. I opened the PGN with notepad and just saved as text. It isn't allowing me to upload a PGN here...
I am using Stockfish "stockfish_14.1_win_x64_avx2.exe"
[Test.txt](https://github.com/mptedesco/python-chess-analysis/files/7865446/Test.txt)

**Comment by infinitless** [comment]
I commented # engine.quit() - a new error came
File "C:...Chess\main.py", line 564, in <module>
    frequency: int = int(round(max(x) / 50, 0))  # If the game has so many moves that the labels would overlap, change
ValueError: max() arg is an empty sequence


I also tried to google the solution to this and wrote Max(x, default = 0) But that doesn't work and gives new errors!!!

**Comment by cja000** [comment]
Hi,
I just test it and worked fine.
Here is the Pandas dataframe that come out:
[test.csv](https://github.com/mptedesco/python-chess-analysis/files/7877300/test.csv)

Try to put a `print(data_for_df)` after `node = next_node` to see in which move it is failing.

**Comment by infinitless** [comment]
Oh ok. Not sure what is happening. Maybe I should try Jupyter instead of PyCharm?! Also does copy pasting into pyCharm work? I don't know how to run code found on Github except by copy-pasting...

**Comment by infinitless** [comment]
@mptedesco Can you please approve/merge the good work done by @cja000 into the file so it's easy to download or copy paste and run. Thanks!!!

**Comment by infinitless** [comment]
I finally got it running till the point it outputs a table. That, I guess is good enough for me as the original issue was to get it working with the new chess module. Thanks @cja000

**Comment by cja000** [comment]
> I finally got it running till the point it outputs a table. That, I guess is good enough for me as the original issue was to get it working with the new chess module. Thanks @cja000

What was the problem?
How did you solve it?

**Comment by infinitless** [comment]
> Hi, I just test it and worked fine. Here is the Pandas dataframe that come out: [test.csv](https://github.com/mptedesco/python-chess-analysis/files/7877300/test.csv)
> 
> Try to put a `print(data_for_df)` after `node = next_node` to see in which move it is failing.

I only ran the code till this line and captured output in a csv. Anything after that gives weird errors! Maybe I will add the rest slowly and block by block. Info_Handler seems to be a problem since in the new chess library it is not used!

**Comment by cja000** [comment]
> > Hi, I just test it and worked fine. Here is the Pandas dataframe that come out: [test.csv](https://github.com/mptedesco/python-chess-analysis/files/7877300/test.csv)
> > Try to put a `print(data_for_df)` after `node = next_node` to see in which move it is failing.
> 
> I only ran the code till this line and captured output in a csv. Anything after that gives weird errors! Maybe I will add the rest slowly and block by block. Info_Handler seems to be a problem since in the new chess library it is not used!

Ok
I just adapted until that point.
I will try to continue with the rest to be able to plot it (Maybe I will change to Plotly :))

**Comment by infinitless** [comment]
That would be great!!! Till that point the code is a bit meaningless - as you can see from one output of a game with only 4 sample moves. The factors are summed up for both sides - which is of no use actually...
Index,Ply,Side,Move,Centi_pawns,Mate,Centi_pawns_delta,Suggested,Depth,Material,Development,Mobility,Control,Tension,Safety
0,1,W,a4,24,,-6,e4,23,0,16,1,2,0,0.03125
1,2,B,a5,28,,4,Nf6,25,0,16,0,0,0,0.0
2,3,W,h4,72,,44,e4,25,0,16,1,2,0,0.03125
3,4,B,h5,84,,12,e5,24,0,16,0,0,0,0.0

**Comment by infinitless** [comment]
If you want to fork it I can offer advice on the theory of what the author is trying to achieve in this code :)
